// @include ../modules/Ajax.js
// @include ../modules/Append.js
// @include ../modules/Attributes.js
// @include ../modules/Classes.js
// @include ../modules/Clone.js
// @include ../modules/CSS.js
// @include ../modules/Data.js
// @include ../modules/Debounce.js
// @include ../modules/Dimensions.js
// @include ../modules/Display.js
// @include ../modules/DoubleTap.js
// @include ../modules/Each.js
// @include ../modules/Eq.js
// @include ../modules/Events.js
// @include ../modules/Filtering.js
// @include ../modules/Focus.js
// @include ../modules/Get.js
// @include ../modules/HTML.js
// @include ../modules/Insert.js
// @include ../modules/Mouseable.js
// @include ../modules/Offset.js
// @include ../modules/Prepend.js
// @include ../modules/Ready.js
// @include ../modules/Remove.js
// @include ../modules/ReplaceWith.js
// @include ../modules/Resize.js
// @include ../modules/Scroll.js
// @include ../modules/Submit.js
// @include ../modules/Traversing.js
// @include ../modules/Trigger.js
// @include ../modules/Value.js
// @include ../modules/Wrap.js